In [1]:
import numpy as np

In [2]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [3]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [4]:
np.arange(2,100,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68,
       70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [5]:
np.ones(5)*10

array([10., 10., 10., 10., 10.])

In [6]:
arr=np.arange(1,17).reshape(4,4)
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [7]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [8]:
np.random.rand()*5 # 0 il 5 arasında rasgele değer üretiyor


1.1551356854462709

In [9]:
np.random.randn(5,5)

array([[ 1.40915584, -0.3194322 ,  0.5638912 , -0.9058803 , -0.00661926],
       [ 0.2288257 ,  0.16306147, -1.19894216, -0.05788426,  0.24432314],
       [-0.05597383, -0.7224164 , -0.94223054,  0.37583175,  1.11757997],
       [-0.15604866, -0.22004776,  1.13507063,  0.00702998,  0.40950834],
       [-0.4935383 , -1.91971535, -0.64147503,  0.06087515,  1.08439403]])

In [10]:
np.linspace(1,5,20)

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [11]:
arr=np.arange(1,101).reshape(10,10)
arr

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [12]:
booleanArray=arr>40
arr[booleanArray].reshape(6,10)

array([[ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [13]:
arr[6:,4:]

array([[ 65,  66,  67,  68,  69,  70],
       [ 75,  76,  77,  78,  79,  80],
       [ 85,  86,  87,  88,  89,  90],
       [ 95,  96,  97,  98,  99, 100]])

In [14]:
arr[0:3,2:4]

array([[ 3,  4],
       [13, 14],
       [23, 24]])

In [15]:
arr[0:3,1:2]

array([[ 2],
       [12],
       [22]])

In [20]:
arr[0:3,1]

array([ 2, 12, 22])

In [28]:
arr[:,9]

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

### array operasyonları

In [30]:
arr1=((np.random.rand(9)*5).astype(int)).reshape(3,3)
arr2 = ((np.random.rand(9) * 5).astype(int)).reshape(3,3)

In [31]:
arr1

array([[0, 2, 3],
       [2, 1, 1],
       [1, 0, 2]])

In [33]:
arr2

array([[0, 0, 3],
       [3, 3, 4],
       [4, 2, 0]])

In [34]:
arr1+arr2

array([[0, 2, 6],
       [5, 4, 5],
       [5, 2, 2]])

In [35]:
arr1*arr2

array([[0, 0, 9],
       [6, 3, 4],
       [4, 0, 0]])

In [39]:
arr1.mean()

1.3333333333333333

In [41]:
arr1.sum()

12