# Numpy

### 1-numpy ın kendi içindeki veri yapısı listelere göre oldukça az yer kaplar!
### 2-arraylerin elemanlarıa erişmek listelere göre daha hızlı.


In [1]:
data_list=[1,2,3]


In [2]:
data_list

[1, 2, 3]

In [3]:
import numpy as np

In [4]:
arr=np.array(data_list) # listemizi nupmy array formatına alıyoruz.

In [5]:
arr

array([1, 2, 3])

In [6]:
data_list2=[[10,20,30],[40,50,60],[70,80,90]]

In [7]:
data_list2

[[10, 20, 30], [40, 50, 60], [70, 80, 90]]

In [8]:
arr2=np.array(data_list2)

In [9]:
arr2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [10]:
arr3=np.array([1,2,3,4,5])

In [11]:
arr3

array([1, 2, 3, 4, 5])

In [12]:
arr3[0]

1

In [13]:
arr2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [14]:
arr2[[2],[2]]

array([90])

In [15]:
arr2[2,2]

90

In [16]:
np.arange(10,20)    # array in "a" sı range() nin rangesi "arange"!

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [17]:
np.zeros(10)  # 10 tane 0 

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [18]:
np.ones(10)  # 10 tane 1

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [19]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [20]:
np.zeros((3,4)) #demet şeklinde vermek zorundayız (())

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [21]:
np.linspace(0,100,5)  #0 ile 100 arasındaki değerleri 5 eşit parçaya bölerek 5 değer üretir

array([  0.,  25.,  50.,  75., 100.])

In [22]:
np.linspace(0,1,6)

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [23]:
np.eye(6) # birim matrisi oluşturma

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [24]:
np.random.randint(0,10) # 0 dahil 10 dahil değil. 0 ile 10 arası rastgele int değer üretir

2

In [25]:
np.random.randint(15) # 0-15 yaşmışım gibi 

0

In [26]:
np.random.randint(1,10,5) # 1-10 arası random 5 değer üret 

array([3, 3, 2, 1, 5])

In [27]:
np.random.randn(5) # ne olduğunu anlamadım

array([ 0.71472079,  1.60288077, -1.11374782, -1.09520235, -0.67424595])

In [28]:
arr=np.arange(25)

In [29]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [30]:
arr.reshape(5,5) # 25 verimizi 5x5 lik bir matrise çevirdik

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [31]:
newArray=np.random.randint(1,100,10)

In [32]:
newArray

array([30, 11, 41, 51, 90, 63, 36, 52, 71, 72])

In [33]:
newArray.max()

90

In [34]:
newArray.min()

11

In [35]:
newArray.mean()

51.7

In [36]:
newArray.sum()

517

## Bu argmin ile argmax ı unutma!

In [37]:
newArray.argmax() # maximum sayı hangi indexte olduğunu gösteriyor ! sınavda çok soruyor


4

In [38]:
newArray.argmin() # en küçük sayı hangi indexte

1

In [39]:
detArray=np.random.randint(1,100,25)

In [40]:
detArray

array([40, 58, 24, 20, 44, 23, 56, 49, 57, 17, 76, 68, 83, 91, 40, 57, 87,
       87, 41, 19, 69, 35,  6, 95, 22])

In [41]:
detArray=detArray.reshape(5,5)

In [42]:
detArray

array([[40, 58, 24, 20, 44],
       [23, 56, 49, 57, 17],
       [76, 68, 83, 91, 40],
       [57, 87, 87, 41, 19],
       [69, 35,  6, 95, 22]])

In [43]:
np.linalg.det(detArray) # matrisin determinantını bulduk

367461987.99999934

In [44]:
detArray2=np.array([[1,2],[3,4]])

In [45]:
detArray2

array([[1, 2],
       [3, 4]])

In [46]:
np.linalg.det(detArray2)

-2.0000000000000004

In [47]:
round(np.linalg.det(detArray2))

-2

## 2. ders


In [48]:
arr=np.arange(1,10)

In [49]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
arr[1]

2

In [51]:
arr[1:5] # 1. indekten 5. indexe kadar git

array([2, 3, 4, 5])

In [52]:
arr[:5] #0. indexten 5. indexe kadar git

array([1, 2, 3, 4, 5])

In [53]:
arr[::2] # 2 atlayarak git

array([1, 3, 5, 7, 9])

In [54]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [55]:
arr[:3]

array([1, 2, 3])

In [56]:
arr[:3]=25 # 0 dan 3 e kadar 25 ata

In [57]:
arr

array([25, 25, 25,  4,  5,  6,  7,  8,  9])

# Burası çokomelli

#### Eğer array1 i array2 ye atama yaparsak pointerlardaki gibi array2 deki değişiklikler array1 e de yansır
#### Aynı pointerlardaki gibi

In [58]:
arr=np.arange(1,10)

In [59]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [60]:
arr2=arr # arr yi arr2 ye atarsak pointerlar mantığıyla çalışır

In [61]:
arr2

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [62]:
arr2[:3]=100

In [63]:
arr2

array([100, 100, 100,   4,   5,   6,   7,   8,   9])

In [64]:
arr

array([100, 100, 100,   4,   5,   6,   7,   8,   9])

### *Eğer pointer gibi çalışmasını istemezsek copy() methodunu kullanırız

In [65]:
arr2=arr.copy()

In [66]:
arr2[:3]=25

In [67]:
arr2

array([25, 25, 25,  4,  5,  6,  7,  8,  9])

In [68]:
arr

array([100, 100, 100,   4,   5,   6,   7,   8,   9])

In [69]:
newArray=np.arange(1,21)

In [70]:
newArray

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [71]:
newArray.reshape(5,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [72]:
newArray

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [73]:
newArray= newArray.reshape(5,4)

In [74]:
newArray

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [75]:
newArray[0,0]

1

In [76]:
newArray[:,:2] # bütün row ları al columnlardan sadece 0 ve 1 i al 

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14],
       [17, 18]])

In [77]:
newArray[:3,:3] # 0,1,2. rowları al 0,1,2. columnları al

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11]])

In [78]:
newArray[:2,:] # ilk 2 row u al columnların hepsini al

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [79]:
newArray[:2] # eğer yanına hiç birşey yazmazsam da aynı şey oluyor

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

### Çokomelli. Koşullu filtreleme

In [80]:
arr=np.arange(1,11)

In [81]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [82]:
arr>3

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True])

In [83]:
booleanArray=arr>3

In [84]:
booleanArray

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True])

In [85]:
arr[booleanArray] # false olan değerleri arrayden atıp sadece True olan değerleri yazdırır. Filtreleme yapmış oluruz

array([ 4,  5,  6,  7,  8,  9, 10])

## 3.Ders

In [86]:
arr1=np.array([10,20,30,40,50,60])
arr2=np.array([2,3,4,5,6,7])

In [87]:
arr1+arr2

array([12, 23, 34, 45, 56, 67])

In [88]:
arr1-arr2

array([ 8, 17, 26, 35, 44, 53])

In [89]:
arr1*arr2

array([ 20,  60, 120, 200, 300, 420])

In [90]:
arr1+10

array([20, 30, 40, 50, 60, 70])

In [91]:
arr2-2

array([0, 1, 2, 3, 4, 5])

In [92]:
arr1

array([10, 20, 30, 40, 50, 60])

In [93]:
arr1/3

array([ 3.33333333,  6.66666667, 10.        , 13.33333333, 16.66666667,
       20.        ])

In [94]:
arr1//3

array([ 3,  6, 10, 13, 16, 20], dtype=int32)

In [95]:
arr1

array([10, 20, 30, 40, 50, 60])

In [96]:
np.sqrt(arr1) # karekökünü al

array([3.16227766, 4.47213595, 5.47722558, 6.32455532, 7.07106781,
       7.74596669])